api:
  host: "0.0.0.0"
  port: "8000"
  base_url: "http://localhost:8000"
db:
  host: "localhost"
  port: "5432"
  name: "catatan_keuangan"
  user: "mapple"
  password: "afandy"
auth:
  jwt_private_key : "./.keys/id_rsa_local.pem"
  jwt_public_key : "./.keys/id_rsa_local.pub.pem"

  jwt_lifetime:
    mobile : "1h"
    refreshToken: "12h"